### ISSUE TITLE
Fixing the sec warning

### ISSUE THREAD

**Issue by dominikwilkowski** [govau/ict-procurement-taskforce#3]
The package https://github.com/zurb/panini has a [dep on `marked`](https://github.com/zurb/panini/blob/master/package.json#L21) which is stated as `^0.3.6`. Just delete your `package-lock.json` and `node_modules` folder and rerun `npm i` and it should naturally install `^0.3.9` (latest) which does not have the XSS bug.

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/ict-procurement-taskforce/pull/4. Thanks @dominikwilkowski!
